export default defineNuxtConfig({
  modules: ['nuxt-graphql-client'],
  runtimeConfig: {
    public: {
      // Types are generated by introspecting the running API, so the back must
      // be up when the front is built. GQL_HOST overrides this per environment.
      GQL_HOST: process.env.GQL_HOST ?? 'http://localhost:3779/graphql',
    },
  },
});
