// The endpoint is reached from two different vantage points, which only diverge
// under Docker (everywhere else they both fall back to localhost:3779):
//   - introspectionHost : GraphQL Codegen, at build time, from inside the
//     container — the API answers on the compose network as http://back:3779
//   - clientHost        : the browser, which only knows the published port
// `host` is the server-side one; the site is fully prerendered, so nothing ever
// goes through it. Types are generated by introspecting the running API: the
// back must be up when the front is built.
const graphqlHost = process.env.GQL_HOST ?? 'http://localhost:3779/graphql';

export default defineNuxtConfig({
  modules: ['nuxt-graphql-client'],
  runtimeConfig: {
    public: {
      'graphql-client': {
        clients: {
          default: {
            host: graphqlHost,
            introspectionHost: graphqlHost,
            clientHost: process.env.GQL_CLIENT_HOST ?? graphqlHost,
          },
        },
      },
    },
  },
});
