mutation updateCustomRecipe($input: UpdateCustomRecipeInput!) {
  updateCustomRecipe(input: $input) {
    id
    name
    slot
    ingredients {
      foodId
      grams
    }
    steps
    prepMinutes
    batch
  }
}
